### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by gabriel4649** [ButterCMS/flask-cms-blog-example#2]
It would be great if your example included an example of how to integrate with Disqus just like in: https://buttercms.com/blog/cms-helper-text-and-new-field-types

**Comment by rogerjin12** [comment]
@tatsuhirosatou Thanks, great feedback! Our Ruby/Rails SDKs do include this, we'll work on getting it added to our Python examples.

**Comment by gabriel4649** [comment]
@rogerjin12 Wow, that is great. Thanks!

**Comment by chasecoleman** [comment]
Thanks @tatsuhirosatou 

Resolved in https://github.com/buttercms/buttercms-flask/commit/b6eb126a886005aa1d85ba6fcecb0b5b7026e90a
